#!/usr/bin/env bash
# tansfer a file from your server to remote server

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	#sed -i '$ a \	StrictHostKeyChecking no' /etc/ssh/ssh_config
	sudo scp -i "$4" -o StrictHostKeyChecking=no  "$1" "$3"@"$2":~/
fi
