#!/usr/bin/env bash
#Install and configure nginx server to respond 'Hello World!'

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/#/d' /etc/nginx/sites-available/default
sed -i '/try_file.*/a \\trewrite \^\/redirect_me https://youtube.com permanent;' /etc/nginx/sites-available/default
service nginx restart 
