#!/usr/bin/env bash
# configure HAproxy to send traffic to 2 web servers useing roundrobin algorithm

#apt-get -y update
#apt-get install --no-install-recommends software-properties-common
#add-apt-repository -y ppa:vbernat/haproxy-2.6
#
#apt-get install -y haproxy=2.6.\*

# keep copy of the configuration file
haproxy_conf=/etc/haproxy/haproxy.cfg
if [ ! -f '/etc/haproxy/haproxy.cfg.orig' ]
then
	cp "$haproxy_conf" '/etc/haproxy/haproxy.cfg.orig'
else
	cp '/etc/haproxy/haproxy.cfg.orig' "$haproxy_conf"
fi
# loadbalancing at leayer 4
sed -i 's/mode.*http/mode\ttcp/' "$haproxy_conf"
sed -i 's/option.*httplog/option\ttcplog/' "$haproxy_conf"
# manage HAproxy via init script
sed -i 's/^[#E].*ABLED.*/ENABLED=1/' '/etc/default/haproxy'
# add configuration
echo -e '
frontend lb
	bind 0.0.0.0:80
	default_backend webserver

backend webserver
	balance roundrobin
	mode tcp
	server web-01 54.84.29.152:80 check
	server web-02 18.235.248.36:80 check
' | sudo tee -a "$haproxy_conf"

service haproxy restart
