#!/usr/bin/env bash
# print fizz for multiples of three, buzz for multiples of five
# and fizzbuzz for multiple of 3 and 5

for i in {1..100}
do
	if [ $i -eq 15 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
