#!/usr/bin/env bash
# check if a file exists, its type and its size

if [ -e "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "school" ]
	then
		echo "school is a regular file"
	fi

else
	echo "school file does not exist"
fi
